services:
  postgres:
    image: postgres:17-alpine
    container_name: iam-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    restart: unless-stopped

  portal-postgres:
    image: postgres:17-alpine
    container_name: employee-portal-postgres
    
    environment:
      POSTGRES_DB: ${PORTAL_DB}
      POSTGRES_USER: ${PORTAL_DB_USER}
      POSTGRES_PASSWORD: ${PORTAL_DB_PASSWORD}

    ports:
      - "127.0.0.1:5433:5432"

    volumes:
      - portal_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PORTAL_DB_USER} -d ${PORTAL_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    restart: unless-stopped

  
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: iam-keycloak

    command:
      - start-dev

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"

    ports:
      - "127.0.0.1:8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped

volumes:
  postgres_data:
    name: enterprise_iam_postgres_data

  portal_postgres_data:
    name: employee_portal_postgres_data