"""store access review grant sources

Revision ID: 0ea809ec0194
Revises: 3f29eac2785c
Create Date: 2026-10-08 14:22:18.944909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea809ec0194'
down_revision = '3f29eac2785c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_review_items') as batch_op:
        batch_op.add_column(
            sa.Column('grant_sources', sa.JSON(), nullable=True))

    op.execute(
        "UPDATE access_review_items "
        "SET grant_sources = '[]' "
        "WHERE grant_sources IS NULL"
    )

    with op.batch_alter_table("access_review_items") as batch_op:
        batch_op.alter_column(
            "grant_sources",
            existing_type=sa.JSON(),
            nullable=False,
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_review_items', schema=None) as batch_op:
        batch_op.drop_column('grant_sources')

    # ### end Alembic commands ###
