"""add access review item assignment source

Revision ID: 3f29eac2785c
Revises: eccc0c949c8c
Create Date: 2026-09-22 21:47:46.724057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f29eac2785c'
down_revision = 'eccc0c949c8c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("access_review_items") as batch_op:
        batch_op.add_column(
            sa.Column(
                "assignment_source",
                sa.String(length=20),
                nullable=True,
            )
        )

    items = sa.table(
        "access_review_items",
        sa.column("assignment_source", sa.String(length=20)),
    )

    op.execute(
        items.update().values(assignment_source="direct")
    )

    with op.batch_alter_table("access_review_items") as batch_op:
        batch_op.alter_column(
            "assignment_source",
            existing_type=sa.String(length=20),
            nullable=False,
        )
        batch_op.create_check_constraint(
            "ck_access_review_items_valid_assignment_source",
            "assignment_source IN ('direct', 'inherited', 'both')",
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_review_items', schema=None) as batch_op:
        batch_op.drop_constraint('ck_access_review_items_valid_assignment_source', type_='check')
        batch_op.drop_column('assignment_source')

    # ### end Alembic commands ###
