"""add managed roles table

Revision ID: b56153280185
Revises: f0ba300bfaec
Create Date: 2026-09-06 22:58:11.002501

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b56153280185"
down_revision = "f0ba300bfaec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "managed_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_name", sa.String(length=100), nullable=False),
        sa.Column("role_name", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("is_privileged", sa.Boolean(), nullable=False),
        sa.Column("assignment_mode", sa.String(length=20), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column("review_interval_days", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "client_name", "role_name", name="uq_managed_roles_client_name_role_name"
        ),
        sa.UniqueConstraint("role_name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("managed_roles")
    # ### end Alembic commands ###
