"""add segregation of duties rules

Revision ID: ebd443f2cd0e
Revises: b56153280185
Create Date: 2026-09-06 23:19:38.410834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd443f2cd0e'
down_revision = 'b56153280185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sod_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('first_role_id', sa.Integer(), nullable=False),
    sa.Column('second_role_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('deny', 'requires_review')", name='ck_sod_rules_valid_outcome'),
    sa.CheckConstraint('first_role_id < second_role_id', name='ck_sod_rules_role_order'),
    sa.ForeignKeyConstraint(['first_role_id'], ['managed_roles.id'], ),
    sa.ForeignKeyConstraint(['second_role_id'], ['managed_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_role_id', 'second_role_id', name='uq_sod_rules_role_pair'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sod_rules')
    # ### end Alembic commands ###
