"""add access review campaigns and items

Revision ID: eccc0c949c8c
Revises: c11431e934a2
Create Date: 2026-09-12 23:34:28.982199

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "eccc0c949c8c"
down_revision = "c11431e934a2"
branch_labels = None
depends_on = None


def upgrade():
    """Create access review tables and remove global role-name uniqueness."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=255), nullable=False),
        sa.Column("reviewer_user_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'open', 'completed', 'cancelled')",
            name="ck_access_reviews_valid_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "access_review_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("client_name", sa.String(length=100), nullable=False),
        sa.Column("role_id", sa.String(length=255), nullable=False),
        sa.Column("role_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["access_reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "review_id",
            "user_id",
            "client_name",
            "role_id",
            name="uq_access_review_items_review_user_client_role",
        ),
    )
    with op.batch_alter_table("access_review_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_access_review_items_review_id"), ["review_id"], unique=False
        )

    with op.batch_alter_table("managed_roles", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("managed_roles_role_name_key"), type_="unique"
        )

    # ### end Alembic commands ###


def downgrade():
    """Drop access review tables and restore global role-name uniqueness."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("managed_roles", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("managed_roles_role_name_key"),
            ["role_name"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("access_review_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_access_review_items_review_id"))

    op.drop_table("access_review_items")
    op.drop_table("access_reviews")
    # ### end Alembic commands ###
